---
# this will be installed via repository, so set those up and install

- name: install| scrape http://get.opera.com/ftp/pub/opera/desktop for latest version
  uri:
    url: http://get.opera.com/ftp/pub/opera/desktop
    return_content: true
  register: versions
- name: install| set version
  set_fact:
    version: "{{ versions.content.split('\n') | select('search', 'href') | list | last | regex_replace('.*>(.*)/</a>.*', '\\1') }}"

# the rpm package is here: http://get.opera.com/ftp/pub/opera/desktop/{{ version }}/linux/opera-stable_{{ version }}_amd64.rpm
- name: do these tasks for RedHat-y systems
  block:
    - name: install|rpm| install the package from the internet
      yum:
        name: http://get.opera.com/ftp/pub/opera/desktop/{{ version }}/linux/opera-stable_{{ version }}_amd64.rpm
        state: present
  when: ansible_os_family == "RedHat"

# the deb package is here: http://get.opera.com/ftp/pub/opera/desktop/{{ version }}/linux/opera-stable_{{ version }}_amd64.deb
- name: do these tasks for Ubuntu systems
  block:
    - name: install|deb| install the package from the internet
      apt:
        deb: http://get.opera.com/ftp/pub/opera/desktop/{{ version }}/linux/opera-stable_{{ version }}_amd64.deb
        state: present
  when: ansible_os_family == "Debian"
