---
# this will be installed via repository, so set those up and install

- name: install| scrape http://get.opera.com/ftp/pub/opera/desktop for latest version
  uri:
    url: http://get.opera.com/ftp/pub/opera/desktop
    return_content: true
  register: versions
- name: install| set latest_version
  set_fact:
    version: "{{ versions.content.split('\n') | select('search', 'href') | list | last | regex_replace('.*>(.*)/</a>.*', '\\1') }}"
    prior_index: "{{ (versions.content.split('\n') | select('search', 'href') | list | length) - 2 }}"

- name: install| see if linux exists for {{ version }}
  uri:
    url:  http://get.opera.com/ftp/pub/opera/desktop/{{ version }}/linux
  register: http_response
  failed_when: false

- name: install|block| test version for linux
  block:
  - name: install| grab prior_version just in case
    set_fact:
      prior_version: "{{ (versions.content.split('\n') | select('search', 'href') | list)[prior_index|int] | regex_replace('.*>(.*)/</a>.*', '\\1') }}"
    register: set_prior_version
  when: http_response.status != 200

# because of an odd "expected" behavior, workaround:
#  https://github.com/ansible/ansible/issues/17500#issuecomment-246370020
- name: install|unavailable| set the version to the previous one only if latest is not available
  set_fact:
    version: "{{ prior_version }}"
  when: set_prior_version is not skipped

# the rpm package is here: http://get.opera.com/ftp/pub/opera/desktop/{{ version }}/linux/opera-stable_{{ version }}_amd64.rpm
- name: do these tasks for RedHat-y systems
  block:
    - name: install|rpm| install the package from the internet
      yum:
        name: http://get.opera.com/ftp/pub/opera/desktop/{{ version }}/linux/opera-stable_{{ version }}_amd64.rpm
        state: present
  when: ansible_os_family == "RedHat"

# the deb package is here: http://get.opera.com/ftp/pub/opera/desktop/{{ version }}/linux/opera-stable_{{ version }}_amd64.deb
- name: do these tasks for Ubuntu systems
  block:
    - name: install|deb| install the package from the internet
      apt:
        deb: http://get.opera.com/ftp/pub/opera/desktop/{{ version }}/linux/opera-stable_{{ version }}_amd64.deb
        state: present
  when: ansible_os_family == "Debian"
